<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ajax extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
		
		
        $this->load->model('M_user');
        $this->load->library('form_validation');
    }

	public function user()
    {
		$id_admin = $_POST['id_admin'];
		$reponse = array(
                'csrfName' => $this->security->get_csrf_token_name(),
                'csrfHash' => $this->security->get_csrf_hash()
                );
			
		
		$data = array(
			'is_login' => 0,		
		);
		$this->M_user->update($id_admin, $data);
        echo json_encode($reponse); 
	}

	
    

}

/* End of file User.php */
/* Location: ./application/controllers/User.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-09-24 11:32:48 */
/* http://harviacode.com */