<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_inboxfile extends CI_Model
{

    public $table = 'inboxfile';
    public $id = 'id_inboxfile';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_inboxfile', $q);
	$this->db->or_like('id_inbox', $q);
	$this->db->or_like('nm_file', $q);
	$this->db->or_like('file', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('user', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_inboxfile', $q);
	$this->db->or_like('id_inbox', $q);
	$this->db->or_like('nm_file', $q);
	$this->db->or_like('file', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('user', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_inboxfile.php */
/* Location: ./application/models/M_inboxfile.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-30 05:51:54 */
/* http://harviacode.com */